# Generated by Django 5.2 on 2025-05-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
