# Generated by Django 5.2 on 2025-06-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_message_receiver_alter_item_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='dismissed_by_seller',
            field=models.BooleanField(default=False),
        ),
    ]
